[package]
name = "generate-schema"
version = "0.1.0"
edition = "2024"

[dependencies]
schemars = "1.0.4"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
wsfork_events = { path ="../../mods/mod_wsfork/wsfork_events" }

