[workspace]

members = [
    "freeswitch_sys",
    "freeswitch_rs",
    "freeswitch_rs_macros",
    "mods/mod_hello_world",
    "tools/generate-schema",
    "mods/mod_wsfork/wsfork_events", 
    "mods/mod_wsfork/mod_wsfork", 
]
